version: '3.8'

services:

  mysql_db:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql

volumes: 
  db:
    driver: local
