version: '3.8'

services:

  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/postgresql
  redis:
    container_name: redis
    image: "redis:6.2-alpine"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - cache:/data
 
volumes: 
  db:
  cache:
    driver: local
